// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorConnect.Infrastructure.SqlServer.Persistence;

#nullable disable

namespace TutorConnect.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260813030000_AddBusinessSchemaV12")]
    partial class AddBusinessSchemaV12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TutorConnect.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens", (string)null);
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Admin', 'Tutor', 'Student')");

                            t.HasCheckConstraint("CK_Users_Status", "[Status] IN ('Active', 'Locked', 'Inactive')");
                        });
                });


            modelBuilder.Entity("TutorConnect.Domain.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");
                    b.HasIndex("Code").IsUnique();
                    b.HasIndex("Name").IsUnique();
                    b.HasIndex("IsActive", "Name");
                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subjects_Code_NotBlank", "NULLIF(LTRIM(RTRIM([Code])), '') IS NOT NULL");
                            t.HasCheckConstraint("CK_Subjects_Name_NotBlank", "NULLIF(LTRIM(RTRIM([Name])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorProfile", b =>
                {
                    b.Property<long>("UserId").HasColumnType("bigint");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<short>("ExperienceYears").HasColumnType("smallint");

                    b.Property<string>("Qualification")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc").HasColumnType("datetime2(0)");
                    b.Property<long?>("ReviewedByAdminId").HasColumnType("bigint");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("SubmittedAtUtc").HasColumnType("datetime2(0)");

                    b.Property<string>("VerificationDocumentUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("UserId");
                    b.HasIndex("ApprovalStatus");
                    b.HasIndex("ReviewedByAdminId").HasFilter("[ReviewedByAdminId] IS NOT NULL");

                    b.ToTable("TutorProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_TutorProfiles_ApprovalStatus", "[ApprovalStatus] IN ('Draft', 'Pending', 'Approved', 'Rejected', 'Suspended')");
                            t.HasCheckConstraint("CK_TutorProfiles_ApprovalFields", "([ApprovalStatus] = 'Draft' AND [SubmittedAtUtc] IS NULL AND [ReviewedByAdminId] IS NULL AND [ReviewedAtUtc] IS NULL) OR ([ApprovalStatus] = 'Pending' AND [SubmittedAtUtc] IS NOT NULL AND [ReviewedByAdminId] IS NULL AND [ReviewedAtUtc] IS NULL) OR ([ApprovalStatus] = 'Approved' AND [SubmittedAtUtc] IS NOT NULL AND [ReviewedByAdminId] IS NOT NULL AND [ReviewedAtUtc] IS NOT NULL) OR ([ApprovalStatus] IN ('Rejected', 'Suspended') AND [SubmittedAtUtc] IS NOT NULL AND [ReviewedByAdminId] IS NOT NULL AND [ReviewedAtUtc] IS NOT NULL AND NULLIF(LTRIM(RTRIM([ReviewNote])), '') IS NOT NULL)");
                            t.HasCheckConstraint("CK_TutorProfiles_ExperienceYears", "[ExperienceYears] BETWEEN 0 AND 80");
                            t.HasCheckConstraint("CK_TutorProfiles_ReviewChronology", "[ReviewedAtUtc] IS NULL OR ([SubmittedAtUtc] IS NOT NULL AND [ReviewedAtUtc] >= [SubmittedAtUtc])");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorSubject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FeePerSessionCredits").HasColumnType("int");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<long>("SubjectId").HasColumnType("bigint");

                    b.Property<string>("TeachingLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("TutorId").HasColumnType("bigint");

                    b.HasKey("Id");
                    b.HasIndex("SubjectId", "TeachingLevel", "IsActive", "FeePerSessionCredits");
                    b.HasIndex("TutorId", "IsActive");
                    b.HasIndex("TutorId", "SubjectId", "TeachingLevel").IsUnique();

                    b.ToTable("TutorSubjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_TutorSubjects_Fee", "[FeePerSessionCredits] > 0");
                            t.HasCheckConstraint("CK_TutorSubjects_TeachingLevel_NotBlank", "NULLIF(LTRIM(RTRIM([TeachingLevel])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek").HasColumnType("int");
                    b.Property<TimeOnly>("EndTime").HasColumnType("time(0)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<TimeOnly>("StartTime").HasColumnType("time(0)");
                    b.Property<long>("TutorId").HasColumnType("bigint");

                    b.HasKey("Id");
                    b.HasIndex("TutorId", "DayOfWeek", "StartTime", "EndTime").IsUnique();
                    b.HasIndex("TutorId", "IsActive", "DayOfWeek");

                    b.ToTable("TutorAvailabilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_TutorAvailabilities_DayOfWeek", "[DayOfWeek] BETWEEN 0 AND 6");
                            t.HasCheckConstraint("CK_TutorAvailabilities_Time", "[EndTime] > [StartTime]");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CancelledByUserId").HasColumnType("bigint");
                    b.Property<int>("CreditCost").HasColumnType("int");
                    b.Property<DateTime>("EndTimeUtc").HasColumnType("datetime2(0)");
                    b.Property<string>("MeetingUrl").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<DateTime>("StartTimeUtc").HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusReason").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<long>("StudentId").HasColumnType("bigint");
                    b.Property<string>("StudentNote").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<long>("TutorSubjectId").HasColumnType("bigint");

                    b.HasKey("Id");
                    b.HasIndex("CancelledByUserId").HasFilter("[CancelledByUserId] IS NOT NULL");
                    b.HasIndex("Status", "StartTimeUtc");
                    b.HasIndex("StudentId", "Status", "StartTimeUtc", "EndTimeUtc");
                    b.HasIndex("TutorSubjectId", "Status", "StartTimeUtc", "EndTimeUtc");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_CreditCost", "[CreditCost] > 0");
                            t.HasCheckConstraint("CK_Bookings_Status", "[Status] IN ('Pending', 'Confirmed', 'Rejected', 'Cancelled', 'Completed')");
                            t.HasCheckConstraint("CK_Bookings_StatusFields", "([Status] = 'Cancelled' AND [CancelledByUserId] IS NOT NULL AND NULLIF(LTRIM(RTRIM([StatusReason])), '') IS NOT NULL) OR ([Status] = 'Rejected' AND [CancelledByUserId] IS NULL AND NULLIF(LTRIM(RTRIM([StatusReason])), '') IS NOT NULL) OR ([Status] IN ('Pending', 'Confirmed', 'Completed') AND [CancelledByUserId] IS NULL AND [StatusReason] IS NULL)");
                            t.HasCheckConstraint("CK_Bookings_Time", "[EndTimeUtc] > [StartTimeUtc]");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.RescheduleRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId").HasColumnType("bigint");
                    b.Property<DateTime>("OriginalEndTimeUtc").HasColumnType("datetime2(0)");
                    b.Property<DateTime>("OriginalStartTimeUtc").HasColumnType("datetime2(0)");
                    b.Property<DateTime>("ProposedEndTimeUtc").HasColumnType("datetime2(0)");
                    b.Property<DateTime>("ProposedStartTimeUtc").HasColumnType("datetime2(0)");
                    b.Property<string>("Reason").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<DateTime>("RequestedAtUtc").HasColumnType("datetime2(0)");
                    b.Property<long>("RequestedByUserId").HasColumnType("bigint");
                    b.Property<long?>("RespondedByUserId").HasColumnType("bigint");
                    b.Property<string>("ResponseNote").HasMaxLength(1000).HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");
                    b.HasIndex("BookingId").IsUnique().HasFilter("[Status] = 'Pending'");
                    b.HasIndex("BookingId", "Status", "RequestedAtUtc");
                    b.HasIndex("RequestedByUserId", "RequestedAtUtc");
                    b.HasIndex("RespondedByUserId").HasFilter("[RespondedByUserId] IS NOT NULL");

                    b.ToTable("RescheduleRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_RescheduleRequests_DifferentUsers", "[RespondedByUserId] IS NULL OR [RespondedByUserId] <> [RequestedByUserId]");
                            t.HasCheckConstraint("CK_RescheduleRequests_OriginalTime", "[OriginalEndTimeUtc] > [OriginalStartTimeUtc]");
                            t.HasCheckConstraint("CK_RescheduleRequests_ProposedTime", "[ProposedEndTimeUtc] > [ProposedStartTimeUtc]");
                            t.HasCheckConstraint("CK_RescheduleRequests_Status", "[Status] IN ('Pending', 'Accepted', 'Rejected', 'Cancelled')");
                            t.HasCheckConstraint("CK_RescheduleRequests_StatusFields", "([Status] = 'Pending' AND [RespondedByUserId] IS NULL AND [ResponseNote] IS NULL) OR ([Status] IN ('Accepted', 'Rejected') AND [RespondedByUserId] IS NOT NULL) OR ([Status] = 'Cancelled' AND [RespondedByUserId] IS NULL AND [ResponseNote] IS NULL)");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.LearningGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description").HasMaxLength(1500).HasColumnType("nvarchar(1500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("StudentId").HasColumnType("bigint");
                    b.Property<DateOnly?>("TargetDate").HasColumnType("date");
                    b.Property<string>("Title").IsRequired().HasMaxLength(250).HasColumnType("nvarchar(250)");
                    b.Property<long>("TutorSubjectId").HasColumnType("bigint");

                    b.HasKey("Id");
                    b.HasIndex("StudentId", "Status");
                    b.HasIndex("TutorSubjectId", "Status");

                    b.ToTable("LearningGoals", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningGoals_Status", "[Status] IN ('NotStarted', 'InProgress', 'Completed', 'Cancelled')");
                            t.HasCheckConstraint("CK_LearningGoals_Title_NotBlank", "NULLIF(LTRIM(RTRIM([Title])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.LearningMilestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<long>("LearningGoalId").HasColumnType("bigint");
                    b.Property<short>("OrderNumber").HasColumnType("smallint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("TargetDate").HasColumnType("date");
                    b.Property<string>("Title").IsRequired().HasMaxLength(250).HasColumnType("nvarchar(250)");

                    b.HasKey("Id");
                    b.HasIndex("LearningGoalId", "OrderNumber").IsUnique();
                    b.HasIndex("LearningGoalId", "Status");

                    b.ToTable("LearningMilestones", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningMilestones_OrderNumber", "[OrderNumber] > 0");
                            t.HasCheckConstraint("CK_LearningMilestones_Status", "[Status] IN ('NotStarted', 'InProgress', 'Completed', 'Cancelled')");
                            t.HasCheckConstraint("CK_LearningMilestones_Title_NotBlank", "NULLIF(LTRIM(RTRIM([Title])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.SessionProgress", b =>
                {
                    b.Property<long>("BookingId").HasColumnType("bigint");
                    b.Property<decimal>("GoalProgressPercent").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
                    b.Property<long>("LearningGoalId").HasColumnType("bigint");
                    b.Property<decimal?>("MaxScore").HasPrecision(7, 2).HasColumnType("decimal(7,2)");
                    b.Property<decimal?>("Score").HasPrecision(7, 2).HasColumnType("decimal(7,2)");
                    b.Property<string>("TutorComment").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");

                    b.HasKey("BookingId");
                    b.HasIndex("LearningGoalId", "BookingId");

                    b.ToTable("SessionProgress", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionProgress_GoalProgress", "[GoalProgressPercent] BETWEEN 0 AND 100");
                            t.HasCheckConstraint("CK_SessionProgress_Score", "([Score] IS NULL AND [MaxScore] IS NULL) OR ([Score] IS NOT NULL AND [MaxScore] IS NOT NULL AND [MaxScore] > 0 AND [Score] >= 0 AND [Score] <= [MaxScore])");
                            t.HasCheckConstraint("CK_SessionProgress_TutorComment_NotBlank", "NULLIF(LTRIM(RTRIM([TutorComment])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId").HasColumnType("bigint");
                    b.Property<string>("Comment").HasMaxLength(1500).HasColumnType("nvarchar(1500)");
                    b.Property<byte>("Rating").HasColumnType("tinyint");
                    b.Property<long>("ReviewerId").HasColumnType("bigint");

                    b.HasKey("Id");
                    b.HasIndex("BookingId", "ReviewerId").IsUnique();
                    b.HasIndex("ReviewerId", "BookingId");

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Complaint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminResponse").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<long>("AgainstUserId").HasColumnType("bigint");
                    b.Property<long?>("BookingId").HasColumnType("bigint");
                    b.Property<long>("CreatedByUserId").HasColumnType("bigint");
                    b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("EvidenceUrl").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<DateTime?>("ResolvedAtUtc").HasColumnType("datetime2(0)");
                    b.Property<long?>("ResolvedByAdminId").HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAtUtc").HasColumnType("datetime2(0)");
                    b.Property<string>("Type").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");

                    b.HasKey("Id");
                    b.HasIndex("AgainstUserId", "SubmittedAtUtc");
                    b.HasIndex("BookingId").HasFilter("[BookingId] IS NOT NULL");
                    b.HasIndex("CreatedByUserId", "SubmittedAtUtc");
                    b.HasIndex("ResolvedByAdminId").HasFilter("[ResolvedByAdminId] IS NOT NULL");
                    b.HasIndex("Status", "SubmittedAtUtc");

                    b.ToTable("Complaints", null, t =>
                        {
                            t.HasCheckConstraint("CK_Complaints_Description_NotBlank", "NULLIF(LTRIM(RTRIM([Description])), '') IS NOT NULL");
                            t.HasCheckConstraint("CK_Complaints_DifferentUsers", "[CreatedByUserId] <> [AgainstUserId]");
                            t.HasCheckConstraint("CK_Complaints_ResolutionChronology", "[ResolvedAtUtc] IS NULL OR [ResolvedAtUtc] >= [SubmittedAtUtc]");
                            t.HasCheckConstraint("CK_Complaints_ResolutionFields", "([Status] IN ('Open', 'InReview') AND [AdminResponse] IS NULL AND [ResolvedByAdminId] IS NULL AND [ResolvedAtUtc] IS NULL) OR ([Status] IN ('Resolved', 'Rejected') AND NULLIF(LTRIM(RTRIM([AdminResponse])), '') IS NOT NULL AND [ResolvedByAdminId] IS NOT NULL AND [ResolvedAtUtc] IS NOT NULL)");
                            t.HasCheckConstraint("CK_Complaints_Status", "[Status] IN ('Open', 'InReview', 'Resolved', 'Rejected')");
                            t.HasCheckConstraint("CK_Complaints_Type_NotBlank", "NULLIF(LTRIM(RTRIM([Type])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorProfile", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.User", "ReviewedByAdmin")
                        .WithMany("ReviewedTutorProfiles")
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TutorConnect.Domain.Entities.User", "User")
                        .WithOne("TutorProfile")
                        .HasForeignKey("TutorConnect.Domain.Entities.TutorProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReviewedByAdmin");
                    b.Navigation("User");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorSubject", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.Subject", "Subject")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.TutorProfile", "Tutor")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subject");
                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorAvailability", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.TutorProfile", "Tutor")
                        .WithMany("TutorAvailabilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.User", "CancelledByUser")
                        .WithMany("CancelledBookings")
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TutorConnect.Domain.Entities.User", "Student")
                        .WithMany("StudentBookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.TutorSubject", "TutorSubject")
                        .WithMany("Bookings")
                        .HasForeignKey("TutorSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CancelledByUser");
                    b.Navigation("Student");
                    b.Navigation("TutorSubject");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.RescheduleRequest", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.Booking", "Booking")
                        .WithMany("RescheduleRequests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.User", "RequestedByUser")
                        .WithMany("RequestedRescheduleRequests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.User", "RespondedByUser")
                        .WithMany("RespondedRescheduleRequests")
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Booking");
                    b.Navigation("RequestedByUser");
                    b.Navigation("RespondedByUser");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.LearningGoal", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.User", "Student")
                        .WithMany("LearningGoals")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.TutorSubject", "TutorSubject")
                        .WithMany("LearningGoals")
                        .HasForeignKey("TutorSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");
                    b.Navigation("TutorSubject");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.LearningMilestone", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.LearningGoal", "LearningGoal")
                        .WithMany("LearningMilestones")
                        .HasForeignKey("LearningGoalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                    b.Navigation("LearningGoal");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.SessionProgress", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.Booking", "Booking")
                        .WithOne("SessionProgress")
                        .HasForeignKey("TutorConnect.Domain.Entities.SessionProgress", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.LearningGoal", "LearningGoal")
                        .WithMany("SessionProgresses")
                        .HasForeignKey("LearningGoalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");
                    b.Navigation("LearningGoal");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Review", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");
                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("TutorConnect.Domain.Entities.User", "AgainstUser")
                        .WithMany("ComplaintsAgainstUser")
                        .HasForeignKey("AgainstUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.Booking", "Booking")
                        .WithMany("Complaints")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TutorConnect.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedComplaints")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TutorConnect.Domain.Entities.User", "ResolvedByAdmin")
                        .WithMany("ResolvedComplaints")
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AgainstUser");
                    b.Navigation("Booking");
                    b.Navigation("CreatedByUser");
                    b.Navigation("ResolvedByAdmin");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Subject", b =>
                {
                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorProfile", b =>
                {
                    b.Navigation("TutorAvailabilities");
                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.TutorSubject", b =>
                {
                    b.Navigation("Bookings");
                    b.Navigation("LearningGoals");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Complaints");
                    b.Navigation("RescheduleRequests");
                    b.Navigation("Reviews");
                    b.Navigation("SessionProgress");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.LearningGoal", b =>
                {
                    b.Navigation("LearningMilestones");
                    b.Navigation("SessionProgresses");
                });

            modelBuilder.Entity("TutorConnect.Domain.Entities.User", b =>
                {
                    b.Navigation("CancelledBookings");
                    b.Navigation("ComplaintsAgainstUser");
                    b.Navigation("CreatedComplaints");
                    b.Navigation("LearningGoals");
                    b.Navigation("RefreshTokens");
                    b.Navigation("RequestedRescheduleRequests");
                    b.Navigation("ResolvedComplaints");
                    b.Navigation("RespondedRescheduleRequests");
                    b.Navigation("ReviewedTutorProfiles");
                    b.Navigation("Reviews");
                    b.Navigation("StudentBookings");
                    b.Navigation("TutorProfile");
                });
#pragma warning restore 612, 618
        }

    }
}
